[directory]
style = "bold dimmed blue"
truncation_length = 8

[character]
success_symbol = "[ð–¹¬](purple)"
error_symbol = "[âœ—](bold red)"

[username]
style_user = "bold purple dimmed"

[container]
disabled = true

